### ISSUE TITLE
Connect pipe timeout on Windows

### ISSUE THREAD

**Issue by inlann** [kldzj/named-pipes#5]
Hello:

So glad to find this awesome module 🤩🤩

I'm trying to use named pipes between a Javascript application and a Python application on Windows. I created a server in the Python application, but when I tried to connect it in the Javascript application via `createNamedPipe('Foo').createReceiver().connect()`, I got a timeout error: `Error: connect ETIMEDOUT \\.\pipe\Foo at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)`.

The following is the Python application(just a script) I used:

```Python
# #!/usr/bin/python3
# #-*- coding:utf-8 -*-

import time
import sys
import win32pipe, win32file, pywintypes


def pipe_server():
    print("pipe server")
    count = 0
    pipe = win32pipe.CreateNamedPipe(
        r'\\.\pipe\Foo',
        win32pipe.PIPE_ACCESS_DUPLEX,
        win32pipe.PIPE_TYPE_MESSAGE | win32pipe.PIPE_READMODE_MESSAGE | win32pipe.PIPE_WAIT,
        1, 65536, 65536,
        0,
        None)
    try:
        print("waiting for client")
        win32pipe.ConnectNamedPipe(pipe, None)
        print("got client")

        while count < 10:
            print(f"writing message {count}")
            # convert to bytes
            some_data = str.encode(f"{count}")
            win32file.WriteFile(pipe, some_data)
            time.sleep(1)
            count += 1

        print("finished now")
    finally:
        win32file.CloseHandle(pipe)


def pipe_client():
    print("pipe client")
    quit = False

    while not quit:
        try:
            handle = win32file.CreateFile(
                r'\\.\pipe\Foo',
                win32file.GENERIC_READ | win32file.GENERIC_WRITE,
                0,
                None,
                win32file.OPEN_EXISTING,
                0,
                None
            )
            res = win32pipe.SetNamedPipeHandleState(handle, win32pipe.PIPE_READMODE_MESSAGE, None, None)
            if res == 0:
                print(f"SetNamedPipeHandleState return code: {res}")
            while True:
                resp = win32file.ReadFile(handle, 64*1024)
                print(f"message: {resp}")
        except pywintypes.error as e:
            if e.args[0] == 2:
                print("no pipe, trying again in a sec")
                time.sleep(1)
            elif e.args[0] == 109:
                print("broken pipe, bye bye")
                quit = True


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("need s or c as argument")
    elif sys.argv[1] == "s":
        pipe_server()
    elif sys.argv[1] == "c":
        pipe_client()
    else:
        print(f"no can do: {sys.argv[1]}")
```

And my Javascript application code:

```Javascript
    async test(): Promise<void> {
        const pipe = createNamedPipe('Foo');
        const receiver = pipe.createReceiver();

        while (true) {
            console.log('Try to connect the receiver pipe...');
            try {
                await receiver.connect();
                console.log('Receiver pipe connect successfully');
                break;
            } catch {
            }
        }

        receiver.on('data', (chunk: Buffer) => {
            console.log('Received data from python server: ', chunk.toString());
        });
    }
```

I don't know why I get the timeout error when I use `createNamedPipe('Foo').createReceiver().connect()` 😢 

BTW: I tested another NodeJS script using the `net` module and connected it to the Python server and it worked fine:

```Javascript
const net = require('net');

const client = net.createConnection('\\\\.\\pipe\\Foo', () => {
    console.log('connected to server!');
  });
  
  client.on('data', (data) => {
    console.log(data.toString());
  });
  
  client.on('end', () => {
    console.log('disconnected from server');
  });
```

<img width="1869" alt="image" src="https://user-images.githubusercontent.com/33852855/176079455-adc5f77e-d6ab-4a28-b2fc-85a00886274f.png">

How can I fix the timeout error?

Really appreciate!

**Comment by kldzj** [comment]
Thanks for reporting this issue, I'll investigate this and get back to you as soon as I find the time 👍🏻

**Comment by inlann** [comment]
Actually, the `net.createConnection` example does not wait for Python to complete the creation of the Pipe. I tried to put it into a while true loop:

```Javascript
const net = require('net');

function connect() {
    while (true) {
        try {
            console.log('Trying to connect')
            const client = net.createConnection('\\\\.\\pipe\\Foo', () => {
                console.log('connected to server!');
            });

            client.on('data', (data) => {
                console.log(data.toString());
            });

            client.on('end', () => {
                console.log('disconnected from server');
            });

            client.on('error', (error) => {
                console.log('Connect error: ', error);
                connect();  // 
            });
            break;
        } catch (error) {
            console.log('Connect failed: ', error)
        }
    }
}

connect();
```

If I run this node script before Python create the pipe, the error event will be emitted which means the `try-catch` cannot catch the connect error. That's why I called the `connect()` again in the callback function of the error event.

I'm not sure if this is why the `receiver.connect()` failed.

**Comment by inlann** [comment]
This link may help:
https://blog.bitsrc.io/when-try-catch-doesnt-catch-errors-in-node-js-d2f339ed9cf4

**Comment by kldzj** [comment]
Thank you again for raising this issue. It seems that checking for the pipes existence using `existsSync` caused the issue.

This snippet it should work flawlessly using version 2.0.4:

```js
const { createNamedPipe } = require('@kldzj/named-pipes')

const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

async function main() {
    const pipe = createNamedPipe('Foo');
    const receiver = pipe.createReceiver();

    receiver.on('connect', () => console.log('Connected!'));
    receiver.on('close', () => console.log('Connection closed!'));
    receiver.on('timeout', () => console.log('Connection timeout!'));
    receiver.on('error', (error) => console.error(error));

    receiver.on('data', (chunk) => {
        console.log('Received data from python server: ', chunk.toString());
    });

    while (!receiver.isConnected()) {
        try {
            await receiver.connect();
        } catch (e) {
            console.error(e);
            await delay(10);
        }
    }
}

main().catch(e => {
    console.error(e);
    process.exit(1);
})
```

Can you please confirm that it's working as intended for you @inlann? :)

**Comment by inlann** [comment]
> It seems that checking for the pipes existence using existsSync caused the issue.

I think this is right.

I have tested it:

<img width="1607" alt="image" src="https://user-images.githubusercontent.com/33852855/176586773-e93b36c3-a4dc-4c2b-ad41-8a000764e9fe.png">

First: Run the `python test.py s` to start a server pipe.  (The `test.py` is just the script above)
Secend: Run the `node test.js` to check the existence of the pipe will emit the pipe 232 error.

Pipes(such as the `\\.\pipe\Foo`) on Windows are not real files and we can't access it via the File Explorer.

**Comment by inlann** [comment]
> Can you please confirm that it's working as intended for you @inlann? :)

I'll test it 😄

**Comment by inlann** [comment]
There is another question: Can I set size and blocking state of the pipe create by the `createNamedPipe()`?

**Comment by kldzj** [comment]
> There is another question: Can I set size and blocking state of the pipe create by the `createNamedPipe()`?

Sadly that's out of scope for now. Pull requests are welcome though. :)

**Comment by inlann** [comment]
> This snippet it should work flawlessly using version 2.0.4:

I tested the `main()` function without the `main().catch(...)` part, and I got a `Pipe not found` error in the first loop because the Python part needed some time to create the pipe file:

<img width="493" alt="image" src="https://user-images.githubusercontent.com/33852855/176829212-38e1895c-c0e3-4bdd-8de0-3e4a3ca8c215.png">

And then, I still got the ETIMEDOUT error:

<img width="470" alt="image" src="https://user-images.githubusercontent.com/33852855/176829145-9272b9f0-80bd-47d2-a073-c518d5feeb64.png">


There is my code:

```typescript
    private sleep(millisecond: number) {
        return new Promise(resolve => setTimeout(resolve, millisecond));
    }

    async startReceiverPipe(): Promise<void> {
        if (process.platform === 'win32') {
            await this.startReceiverPipeViaFifo();
        } else {
        }
    }

    private async startReceiverPipeViaFifo(): Promise<void> {

        console.log(1111, this.receiverPipe.path);
        this.receiver = this.receiverPipe.createReceiver();

        this.receiver.on('connect', () => console.log('Connected!'));
        this.receiver.on('close', () => console.log('Connection closed!'));
        this.receiver.on('timeout', () => console.log('Connection timeout!'));
        this.receiver.on('error', (error: Error) => console.error(error));

        this.receiver.on('data', (chunk: Buffer) => {
            console.log('VCMB received data from python server: ', chunk.toString());
            this.handleMessage(chunk.toString());
        });

        while (!this.receiver.isConnected()) {
            try {
                console.log('Try to connect python pipe');
                await this.receiver.connect();
            } catch (e) {
                console.error(e);
                await this.sleep(1000);
            }
        }
    }
```

**Comment by kldzj** [comment]
Are you positive you're using the latest version? This error should not be thrown on `win32`.

As long as the `while` loop is still trying to connect you can expect errors, but as they're caught it should just retry until it's connected.

**Comment by inlann** [comment]
Yes, I'm using the version 2.0.4

**Comment by inlann** [comment]
I tested it again out of my project and it worked 👍🏼 

<img width="1570" alt="image" src="https://user-images.githubusercontent.com/33852855/177067060-08e7d2b6-039b-49b3-8864-42264cb61ae0.png">

I'll check my project code 😂
